import { Waves } from 'lucide-react';
import { SOURCE_LABEL } from '../format';
import { useStore } from '../store';
import { C, STATE_COLOR } from '../theme';
import { StatusDot } from './ui';
import s from './shell.module.css';

function UsbLink() {
  const serial = useStore((st) => st.status?.serial.state ?? 'disconnected');
  const silent = useStore((st) => st.status?.serial.silent ?? false);
  const trouble = serial === 'reconnecting' || (serial === 'connected' && silent);
  const color = trouble ? C.danger : serial === 'connected' ? C.cyan : undefined;
  const title = serial === 'connected'
    ? silent ? 'USB serial open, but the device is silent' : 'USB serial connected'
    : serial === 'reconnecting' ? 'USB device lost — reconnecting' : 'USB serial not connected';
  return (
    <span className={s.link} title={title}>
      <StatusDot color={color} blink={trouble} /> USB{trouble && <span style={{ color: C.danger }}>{serial === 'reconnecting' ? ' lost' : ' silent'}</span>}
    </span>
  );
}

function WifiLink() {
  const online = useStore((st) => st.status?.wifi.online ?? false);
  return (
    <span className={s.link} title={online ? 'WiFi telemetry arriving' : 'No WiFi telemetry'}>
      <StatusDot color={online ? C.cyan : undefined} /> WiFi
    </span>
  );
}

function BackendLink() {
  const ws = useStore((st) => st.ws.state);
  const color = ws === 'open' ? C.cyan : ws === 'closed' ? C.danger : undefined;
  const label = ws === 'open' ? 'Link' : ws === 'closed' ? 'Link down' : 'Linking…';
  return (
    <span className={s.link} title="WebSocket link to the telemetry hub">
      <StatusDot color={color} blink={ws !== 'open'} />
      <span style={ws === 'closed' ? { color: C.danger } : undefined}>{label}</span>
    </span>
  );
}

/** Where the numbers on screen come from. Simulated data is never allowed to look real. */
function SourceBadge() {
  const source = useStore((st) => st.latest?.source);
  const stale = useStore((st) => (st.status?.lastRealAgoMs ?? 0) > 2500);
  if (!source) return <span className={`${s.chip} ${s.muted}`}>NO DATA</span>;
  if (source === 'simulated') {
    return <span className={s.simBadge} title="Values are generated by the backend's simulation engine, not a device">SIMULATED</span>;
  }
  if (stale) {
    return <span className={`${s.chip}`} style={{ color: C.danger }} title="Device stopped reporting — values are its last report">STALE · {SOURCE_LABEL[source]}</span>;
  }
  return <span className={s.liveBadge} title="Live device telemetry">LIVE · {SOURCE_LABEL[source]}</span>;
}

function StateChip() {
  const state = useStore((st) => st.latest?.state);
  const cycle = useStore((st) => st.latest?.cycle);
  if (!state) return null;
  const color = STATE_COLOR[state];
  return (
    <>
      <span className={s.stateChip} style={{ color, background: `${color}18` }} aria-live="polite">{state}</span>
      <span className={s.muted}>ping #{cycle}</span>
    </>
  );
}

export function Header() {
  return (
    <header className={s.header}>
      <div className={s.brand}>
        <Waves size={18} color={C.cyan} aria-hidden />
        <h1 className={s.title}>Adaptive Sonar TX — Module Console</h1>
      </div>
      <div className={s.indicators}>
        <SourceBadge />
        <UsbLink />
        <WifiLink />
        <BackendLink />
        <StateChip />
      </div>
    </header>
  );
}
